version: "2"

services:

    app:
      build: .
      volumes:
          - .:/code
      working_dir: /code
      command: bash -c 'set -a && composer ci'
      environment:
        - MYSQL_DATABASE=testdb
        - MYSQL_ROOT_PASSWORD=somePassword
        - SSH_KEY_PRIVATE
      links:
        - sshproxy
        - mysql

    mysql:
      image: mysql:5.6
      environment:
        MYSQL_DATABASE: testdb
        MYSQL_ROOT_PASSWORD: somePassword

    sshproxy:
      build: ./tests/env/sshproxy
      volumes:
          - ./tests/env/sshproxy:/code
      working_dir: /code
      ports:
        - "2222:22"
      links:
        - mysql

    wait:
      image: waisbrot/wait
      depends_on:
        - mysql
      environment:
        - TARGETS=mysql:3306
        - TIMEOUT=200
