app:
  build: .
  volumes:
      - .:/code
  working_dir: /code
  entrypoint: "./phpunit.sh"
  tty: true
  stdin_open: true
  links:
    - sshproxy
    - mysql

mysql:
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: testdb
    MYSQL_ROOT_PASSWORD: somePassword

sshproxy:
  build: ./tests/env/sshproxy
  volumes:
      - ./tests/env/sshproxy:/code
  working_dir: /code
  ports:
    - "2222:22"
  links:
    - mysql
