app:
  build: .
  volumes:
      - .:/code
  working_dir: /code
  command: bash -c 'set -a && source privateKey.env && composer ci'
  environment:
    MYSQL_DATABASE: testdb
    MYSQL_ROOT_PASSWORD: somePassword
  links:
    - sshproxy
    - mysql

mysql:
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: testdb
    MYSQL_ROOT_PASSWORD: somePassword

sshproxy:
  build: ./tests/env/sshproxy
  volumes:
      - ./tests/env/sshproxy:/code
  working_dir: /code
  ports:
    - "2222:22"
  links:
    - mysql
