name: Build on push
on: [ push ]
env:
  SSH_KEY_PRIVATE: ${{ secrets.SSH_KEY_PRIVATE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and run tests
        run: |
          docker-compose run --rm wait
          docker-compose run -e SSH_KEY_PRIVATE --rm app
